[After #105] mgr/dashboard_v2: OSD pages
openattic/ceph pull request #111
Opened 2018-02-19 17:20 UTC by Devp00l

You can now list all osds and see details for each OSD.
The details can be viewed in tabs. You can view attributes, meta data
and histogram of the selected OSD. The details are updating them self
every five seconds.

Signed-off-by: Stephan Müller <smueller@suse.com>

2018-02-19 18:12 UTC, LenzGr commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/osd/osd-performance-histogram/osd-performance-histogram.component.ts
> +  hexdigits(v): string {
This looks like rather generic code. Would it make sense to add this to some commonly shared library instead?

2018-02-19 22:26 UTC, ricardoasmarques commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/osd/osd-performance-histogram/osd-performance-histogram.component.ts
> +import * as _ from 'underscore';
Shouldn't be 'lodash' instead of 'underscore'?

2018-02-19 22:30 UTC, ricardoasmarques requested changes
I've received the following error while trying to access Metadata tab:

![screenshot from 2018-02-19 22-28-22](https://user-images.githubusercontent.com/14297426/36399592-6e587082-15c4-11e8-8836-8e22424e8bed.png)

2018-02-19 22:40 UTC, ricardoasmarques commented
Some notes regarding the usage of this accordion:

![screenshot from 2018-02-19 22-34-39](https://user-images.githubusercontent.com/14297426/36399804-7b371384-15c5-11e8-8e90-cb15a98195d7.png)

- If possible, I would prefer a symbol like we have on breadcrumbs, instead of "->"
- Shouldn't we disable the "collapse" option to prevent the panel from collapsing on click?

2018-02-19 22:42 UTC, ricardoasmarques commented
For me, it was not clear to understand why "Metadata" and "Histogram" tabs were disable when I clicked on a row, shouldn't we use a loading indicator on this tabs?

2018-02-21 13:08 UTC, votdev commented
Do we really need the accordion when in the details area? I do not like it and it displays redundant info, the selected table row is highlighted which should be enough to visualize the origin of the data to the user.

The RGW daemon page only displays the tabs in the details area.
![bildschirmfoto vom 2018-02-21 14-06-40](https://user-images.githubusercontent.com/1897962/36481555-7b945052-1710-11e8-937b-3b4dde3adced.png)

2018-02-21 15:58 UTC, sebastian-philipp commented
Frightening that `GET /api/osd` returns something completely different than `GET /api/osd/0`. Was this already part of `_v1`?

2018-02-21 16:17 UTC, ricardoasmarques commented
@votdev AFAIK accordion is for the case where user selects multiple lines, but let's wait for @Devp00l opinion.

2018-02-21 17:03 UTC, rjfd requested changes

2018-02-21 17:03 UTC, rjfd commented on src/pybind/mgr/dashboard_v2/controllers/osd.py
> +        for id in osds:
you need to you other variable name. `id` will trigger a lint warning. Maybe call it `osd_id`

2018-02-22 15:07 UTC, Devp00l commented
![osd-pages](https://user-images.githubusercontent.com/16167865/36545953-66fb1ff6-17ea-11e8-9017-c7797d73bb77.gif)

2018-02-22 15:24 UTC, sebastian-philipp submitted a review, later dismissed

2018-02-22 16:53 UTC, ricardoasmarques commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.ts
> +import { SortPropDir } from '@swimlane/ngx-datatable';
This import can be removed.

2018-02-22 17:02 UTC, ricardoasmarques submitted a review, later dismissed
Lgtm

2018-02-23 01:08 UTC, tspmelo requested changes

2018-02-23 01:08 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/osd/osd-details/osd-details.component.ts
> +import * as _ from 'lodash';
please reorder the imports. 
You can check the recommended order [here](https://github.com/openattic/ceph/blob/wip-mgr-dashboard_v2/src/pybind/mgr/dashboard_v2/HACKING.rst#frontend-typescript-code-style-guide-recommendations).

2018-02-23 01:08 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.spec.ts
> +import { async, ComponentFixture, TestBed } from '@angular/core/testing';
please reorder the imports. 
You can check the recommended order [here](https://github.com/openattic/ceph/blob/wip-mgr-dashboard_v2/src/pybind/mgr/dashboard_v2/HACKING.rst#frontend-typescript-code-style-guide-recommendations).

2018-02-23 01:08 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/osd/osd-list/osd-list.component.ts
> +import { Component } from '@angular/core';
please reorder the imports. 
You can check the recommended order [here](https://github.com/openattic/ceph/blob/wip-mgr-dashboard_v2/src/pybind/mgr/dashboard_v2/HACKING.rst#frontend-typescript-code-style-guide-recommendations).

2018-02-23 01:08 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/osd/osd.service.spec.ts
> +import { inject, TestBed } from '@angular/core/testing';
please reorder the imports. 
You can check the recommended order [here](https://github.com/openattic/ceph/blob/wip-mgr-dashboard_v2/src/pybind/mgr/dashboard_v2/HACKING.rst#frontend-typescript-code-style-guide-recommendations).

2018-02-23 01:08 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/cluster.module.ts
> +import { HttpClientModule } from '@angular/common/http';
This import can be removed.

2018-02-23 01:08 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/osd/osd-details/osd-details.component.spec.ts
> +import { async, ComponentFixture, TestBed } from '@angular/core/testing';
please reorder the imports. 
You can check the recommended order [here](https://github.com/openattic/ceph/blob/wip-mgr-dashboard_v2/src/pybind/mgr/dashboard_v2/HACKING.rst#frontend-typescript-code-style-guide-recommendations).

2018-02-23 01:08 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/cluster/osd/osd.service.ts
> +  constructor (private http: HttpClient) {}
please add a blank line before and after the constructor.

2018-02-23 01:08 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/shared/datatable/datatable.module.ts
> +import { OsdDetailsComponent } from '../../ceph/cluster/osd/osd-details/osd-details.component';
This import is never used.

2018-02-23 01:08 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/shared/shared.module.ts
> +    ComponentsModule,
This module is being exported 3 times.

2018-02-23 12:14 UTC, tspmelo approved these changes

2018-02-23 12:29 UTC, rjfd approved these changes
lgtm

2018-02-23 12:34 UTC, merged