[WIP][After#116] mgr/dashboard_v2: add mirroring page
openattic/ceph pull request #120
Opened 2018-02-21 01:24 UTC by tspmelo

This PR uses the api provided by #116. 

![localhost_4200_ fh 3](https://user-images.githubusercontent.com/399326/36458227-4d60aea6-169d-11e8-8b35-230b4d6da005.png)

`Signed-off-by: Tiago Melo <tmelo@suse.com>`

2018-02-21 09:36 UTC, votdev requested changes

2018-02-21 09:36 UTC, votdev commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/block/mirroring/mirroring.component.ts
> +    setTimeout(() => {
This should be
```
this.interval = setTimeout(() => {
    this.refresh();
}, 30000);
```

2018-02-21 11:03 UTC, ricardoasmarques commented on src/pybind/mgr/dashboard_v2/frontend/src/app/ceph/block/mirroring/mirroring.component.ts
> +      { prop: 'image_local_count', name: '# Local' },
Number fields should be align to the right.

2018-02-22 13:03 UTC, LenzGr submitted a review, later dismissed

2018-02-22 23:52 UTC, tspmelo commented
Preview, now with data and new column sizes:
![192 168 1 136_4200_ fhd 8](https://user-images.githubusercontent.com/399326/36570719-47336354-182b-11e8-8a6a-32ce4f875aaf.png)

2018-02-23 09:43 UTC, votdev submitted a review, later dismissed

2018-02-23 13:46 UTC, tspmelo commented
I added the error/warning information on the menu:
![192 168 1 136_4200_ fhd 10](https://user-images.githubusercontent.com/399326/36597090-f4eb2990-189f-11e8-9b16-c5ab980c52c7.png)

2018-02-23 13:48 UTC, Devp00l approved these changes
lgtm

2018-02-23 13:56 UTC, LenzGr approved these changes

2018-02-23 13:56 UTC, merged