Various improvements
openattic/ceph pull request #43
Opened 2018-01-29 15:55 UTC by votdev

* Ignore PyCharm debug egg.
* Rename the variable mgr -> mgr_module in the controller classes. The name 'mgr' implies that this is the Ceph manager instead only the dashboard module.
* Rename the variable logger -> log because this method name is used in the MgrModule, thus it makes no sense to introduce another name.

Signed-off-by: Volker Theile <vtheile@suse.com>

2018-01-29 16:10 UTC, sebastian-philipp commented
> Rename the variable logger -> log because this method name is used in the MgrModule, thus it makes
> no sense to introduce another name.

but, a logger is typically called [`logger`](https://docs.python.org/3/howto/logging.html#advanced-logging-tutorial)!

2018-01-29 16:11 UTC, sebastian-philipp requested changes
> Rename the variable logger -> log because this method name is used in the MgrModule, thus it makes
> no sense to introduce another name.

but, a logger is typically called [`logger`](https://docs.python.org/3/howto/logging.html#advanced-logging-tutorial)!

2018-01-29 16:33 UTC, votdev commented
That might be correct, but Ceph is using log, see https://github.com/ceph/ceph/blob/master/src/pybind/mgr/mgr_module.py#L256 for example.

2018-01-29 16:35 UTC, sebastian-philipp commented
But even they call the member `self._logger`!

2018-01-29 17:00 UTC, LenzGr approved these changes

2018-01-30 10:03 UTC, p-na commented on src/pybind/mgr/dashboard_v2/.gitignore
> +*.egg
Can you be a little bit more specific here? Like `*pycharm*.egg` or `*debug*.egg`?

2018-01-30 10:18 UTC, rjfd commented
@votdev @sebastian-philipp please reach a consensus because this PR is renaming important variables that are used in future PRs, otherwise @votdev will have to update this PR for all futures PRs that are merged before this.

2018-01-30 10:57 UTC, s0nea approved these changes

2018-01-30 11:29 UTC, jecluis commented
@sebastian-philipp @votdev fwiw, I do believe normalizing the dashboard's code base around what has already been established makes sense. Either change the logging method in mgr_module.py to something you are happier about (and have that properly reviewed) and then normalize around that, or normalize your code around a log() function as well.
You are free to disregard this advice, but keep in mind that while you are the ones currently developing this code, the dashboard will have other contributors in the near future and you should think how they will better understand your code. Feels silly to use different terms for the same things throughout the code base. That's how you end up with technical debt in the long run.

2018-01-30 11:32 UTC, jecluis requested changes
the commit title should be changed:
1. descriptive title with the component being changed;
2. shorter

2018-01-30 12:52 UTC, closed without merging