mgr/dashboard_v2: Various fixes around return types and content types
openattic/ceph pull request #50
Opened 2018-01-30 15:06 UTC by p-na

Unifies the output format and corresponding content type headers.

2018-01-30 15:09 UTC, sebastian-philipp requested changes

2018-01-30 15:09 UTC, sebastian-philipp commented on src/pybind/mgr/dashboard_v2/tools.py
> +        cherrypy.response.headers['Content-Type'] = 'application/json'
do we still need this one?

2018-01-31 07:45 UTC, rjfd commented
@p-na to fix conflicts of PRs with respect to changes in the master branch (in this case `wip-mgr-dashboard_v2`) you should not merge the latest changes into the PR branch but instead rebase all the PR commits on top of the latest changes of master.

For example, if your git remote repo is called `ceph_openattic`, and assuming your current branch is the PR branch, you should do this:
```
# fetch latest changes from remote
git fetch ceph_openattic
# rebase 
git rebase ceph_openattic/wip-mgr-dashboard_v2
```

If conflicts arise during the rebase, do this:
```
# check which files are in conflict
git status
# edit the files and fix conflicts
git add files_with_fixed_conflicts
# continue the rebase
git rebase --continue
```

Please remove the merge commit and rebase this PR commits on top of the latest changes of `wip-mgr-dashboard_v2`

2018-01-31 08:45 UTC, p-na commented on src/pybind/mgr/dashboard_v2/tools.py
> +        cherrypy.response.headers['Content-Type'] = 'application/json'
Nope, nice find! Removed it.

2018-01-31 09:12 UTC, sebastian-philipp approved these changes

2018-01-31 09:16 UTC, votdev requested changes

2018-01-31 09:16 UTC, votdev commented on src/pybind/mgr/dashboard_v2/tools.py
>  def _json_error_page(status, message, traceback, version):
Maybe you should rename this function to ``json_error_page`` because it is not private anymore.

2018-01-31 09:16 UTC, rjfd requested changes

2018-01-31 09:16 UTC, rjfd commented on src/pybind/mgr/dashboard_v2/module.py
> +from .tools import load_controllers, _json_error_page
please remove the `_` prefix from the function name since it's being used externally to the tools module

2018-01-31 09:29 UTC, s0nea approved these changes

2018-01-31 10:10 UTC, rjfd approved these changes
lgtm

2018-01-31 10:26 UTC, votdev approved these changes

2018-01-31 10:44 UTC, merged