mgr/dashboard_v2: Add support for nested controllers
openattic/ceph pull request #76
Opened 2018-02-07 15:34 UTC by p-na

The `ApiController` decorator is used to define a API endpoints.  This
change will enable to use `/` in paths, so that nested controllers can
be used.

Signed-off-by: Patrick Nawracay <pnawracay@suse.com>

2018-02-07 15:42 UTC, votdev requested changes

2018-02-07 15:42 UTC, votdev commented on src/pybind/mgr/dashboard_v2/module.py
>                  ins = ctrl()
Can you please rename this variable to ``inst`` or ``instance`` (i know it's not part of this PR). The current name doesn't enlight me what it is for on the first look.

2018-02-08 10:09 UTC, sebastian-philipp submitted a review, later dismissed

2018-02-08 11:20 UTC, s0nea submitted a review, later dismissed

2018-02-09 10:35 UTC, sebastian-philipp approved these changes

2018-02-09 10:38 UTC, s0nea approved these changes

2018-02-09 10:43 UTC, votdev approved these changes

2018-02-09 10:46 UTC, merged