mgr/dashboard_v2: Easy table cell transformation
openattic/ceph pull request #90
Opened 2018-02-13 12:44 UTC by Devp00l

The table column definition is extended by "cellTransformation"
property, which is filled through the use of "CellTemplate" enum.
If you have set that, a specific template reference will be used for
the ngx column property "cellTemplate". All references are stored
at the bottom of the data table template.

Signed-off-by: Stephan Müller <smueller@suse.com>

2018-02-13 13:23 UTC, tspmelo commented on src/pybind/mgr/dashboard_v2/frontend/src/app/shared/components/table/table.component.ts
> +  Output, TemplateRef,
break this into 2 lines.

2018-02-13 13:25 UTC, tspmelo requested changes
just needs a minor line break. 
the rest lgtm.

2018-02-13 13:53 UTC, Devp00l commented on src/pybind/mgr/dashboard_v2/frontend/src/app/shared/components/table/table.component.ts
> +  Output, TemplateRef,
done

2018-02-13 16:08 UTC, tspmelo approved these changes

2018-02-13 16:18 UTC, votdev approved these changes

2018-02-14 09:58 UTC, Exotelis approved these changes

2018-02-14 10:01 UTC, merged